export const FORMULARIO_TURNO = 'FORMULARIO_TURNO';
export const AGREGAR_TURNO = 'AGREGAR_TURNO';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';
export const FETCH_CLIMA = 'FETCH_CLIMA';
export const FETCH_COLAS = 'FETCH_COLAS';